export const MOCK_COMPANIES = [
  { id:"c1",  name:"Meridian AI",       website:"meridian.ai",         sector:"AI/ML",            stage:"Seed",     location:"San Francisco, CA", founded:2023, employees:"11-50",  arr:"$0.4M", raised:"$3.2M",  description:"LLM-native workflow automation for financial services compliance teams.",                                              tags:["AI","Fintech","Compliance","B2B SaaS"],        thesisScore:94, signals:[{date:"2024-11",type:"Funding",text:"Raised $3.2M seed led by Sequoia scouts"},{date:"2024-10",type:"Hire",text:"Hired VP Engineering from Palantir"},{date:"2024-09",type:"Launch",text:"Launched beta with 3 enterprise pilots"}] },
  { id:"c2",  name:"Corelink",           website:"corelink.dev",         sector:"Developer Tools",  stage:"Series A", location:"New York, NY",        founded:2022, employees:"51-200", arr:"$2.1M", raised:"$11M",   description:"Infrastructure-as-code platform for multi-cloud database migrations with zero downtime guarantees.",                    tags:["DevTools","Infrastructure","Cloud","B2B"],     thesisScore:81, signals:[{date:"2024-11",type:"Blog",text:"Published whitepaper on zero-downtime migrations"},{date:"2024-10",type:"Partnership",text:"AWS Advanced Partner status awarded"}] },
  { id:"c3",  name:"Pulsar Health",      website:"pulsarhealth.com",     sector:"Health Tech",      stage:"Pre-Seed", location:"Boston, MA",          founded:2024, employees:"1-10",   arr:"$0",    raised:"$800K",  description:"AI-powered early detection of sepsis in ICU patients using continuous vital monitoring.",                              tags:["HealthTech","AI","Hospital","MedDevice"],      thesisScore:77, signals:[{date:"2024-11",type:"Research",text:"Study results: 34% improvement in early detection"}] },
  { id:"c4",  name:"Stackform",          website:"stackform.io",         sector:"Developer Tools",  stage:"Seed",     location:"Austin, TX",          founded:2023, employees:"11-50",  arr:"$0.6M", raised:"$4.5M",  description:"Component-first design system builder with automated React and Tailwind code export.",                                  tags:["DevTools","Design","Frontend","SaaS"],         thesisScore:68, signals:[{date:"2024-10",type:"Launch",text:"Product Hunt #2 of the day"},{date:"2024-09",type:"Milestone",text:"500 paying teams milestone"}] },
  { id:"c5",  name:"Orbis Logistics",    website:"orbislogistics.co",    sector:"Supply Chain",     stage:"Series A", location:"Chicago, IL",         founded:2021, employees:"51-200", arr:"$5.8M", raised:"$18M",   description:"AI freight optimization for last-mile delivery with real-time dynamic routing.",                                         tags:["Logistics","AI","Supply Chain","B2B"],         thesisScore:62, signals:[{date:"2024-11",type:"Funding",text:"Announced $18M Series A"},{date:"2024-08",type:"Hire",text:"Hired COO from UPS Innovation Lab"}] },
  { id:"c6",  name:"Fenix Security",     website:"fenixsec.io",          sector:"Cybersecurity",    stage:"Seed",     location:"Washington, DC",      founded:2023, employees:"11-50",  arr:"$0.9M", raised:"$5M",    description:"Autonomous threat hunting for critical infrastructure using behavioral graph analysis.",                                  tags:["Cybersecurity","AI","Infrastructure","Gov"],   thesisScore:88, signals:[{date:"2024-11",type:"Contract",text:"Signed DOE pilot contract worth $1.2M"},{date:"2024-10",type:"Hire",text:"CISO from NSA joined advisory board"}] },
  { id:"c7",  name:"Cadence Finance",    website:"cadencefinance.com",   sector:"Fintech",          stage:"Seed",     location:"Miami, FL",           founded:2022, employees:"11-50",  arr:"$1.1M", raised:"$6M",    description:"Embedded BNPL infrastructure for B2B software vendors targeting SMBs.",                                                  tags:["Fintech","Embedded Finance","B2B","Payments"],  thesisScore:73, signals:[{date:"2024-10",type:"Partnership",text:"Integrated with 12 SaaS platforms"},{date:"2024-09",type:"Milestone",text:"$40M in GMV processed"}] },
  { id:"c8",  name:"Forma Labs",         website:"formalabs.xyz",        sector:"AI/ML",            stage:"Pre-Seed", location:"Remote",              founded:2024, employees:"1-10",   arr:"$0",    raised:"$1.5M",  description:"Synthetic data generation platform for training domain-specific vision models.",                                          tags:["AI","MLOps","Computer Vision","Data"],         thesisScore:85, signals:[{date:"2024-11",type:"Research",text:"3 top-tier ML conference acceptances"},{date:"2024-10",type:"Hire",text:"Co-founder previously at DeepMind"}] },
  { id:"c9",  name:"Rootbase",           website:"rootbase.earth",       sector:"Climate Tech",     stage:"Seed",     location:"Portland, OR",        founded:2023, employees:"11-50",  arr:"$0.3M", raised:"$3.8M",  description:"Carbon credit verification platform using satellite imagery and ML for nature-based solutions.",                          tags:["Climate","Carbon","Satellite","B2B"],          thesisScore:71, signals:[{date:"2024-10",type:"Launch",text:"Launched public API for carbon registries"},{date:"2024-09",type:"Funding",text:"Grant from USDA Climate Smart program"}] },
  { id:"c10", name:"Vessel AI",          website:"vessel.ai",            sector:"AI/ML",            stage:"Series A", location:"San Francisco, CA",   founded:2022, employees:"51-200", arr:"$3.4M", raised:"$14M",   description:"Revenue intelligence copilot for enterprise sales teams that surfaces churn risk and upsell opportunities.",             tags:["AI","Sales","Revenue","CRM"],                  thesisScore:79, signals:[{date:"2024-11",type:"Funding",text:"Raised $14M Series A from Insight Partners"},{date:"2024-10",type:"Customer",text:"Signed Salesforce as design partner"}] },
  { id:"c11", name:"Trove Robotics",     website:"troverobotics.com",    sector:"Robotics",         stage:"Seed",     location:"Pittsburgh, PA",      founded:2023, employees:"11-50",  arr:"$0",    raised:"$4M",    description:"Autonomous bin-picking robots for e-commerce warehouse sorting with plug-and-play deployment.",                          tags:["Robotics","Warehouse","Automation","Hardware"], thesisScore:59, signals:[{date:"2024-10",type:"Milestone",text:"Deployed first production robot at Flexport"}] },
  { id:"c12", name:"Delphi Analytics",   website:"delphianalytics.io",   sector:"Data & Analytics", stage:"Seed",     location:"London, UK",          founded:2022, employees:"11-50",  arr:"$0.8M", raised:"$4.2M",  description:"Self-serve product analytics for B2B SaaS with automated cohort analysis and anomaly detection.",                        tags:["Analytics","B2B SaaS","PLG","Data"],           thesisScore:76, signals:[{date:"2024-11",type:"Launch",text:"Launched native Snowflake integration"},{date:"2024-09",type:"Hire",text:"VP Product from Amplitude joined"}] },
  { id:"c13", name:"Nexus Bioworks",     website:"nexusbio.com",         sector:"Biotech",          stage:"Series A", location:"Cambridge, MA",       founded:2021, employees:"51-200", arr:"$1.2M", raised:"$22M",   description:"AI-designed protein therapeutics targeting rare autoimmune conditions with novel structure prediction.",                 tags:["Biotech","Drug Discovery","AI","Rare Disease"], thesisScore:55, signals:[{date:"2024-10",type:"Research",text:"IND filing for lead candidate submitted"}] },
  { id:"c14", name:"Hyperion Grid",      website:"hyperiongrid.com",     sector:"Energy Tech",      stage:"Pre-Seed", location:"Houston, TX",         founded:2024, employees:"1-10",   arr:"$0",    raised:"$2M",    description:"Software-defined EV charging orchestration for fleet operators optimizing cost and grid load.",                          tags:["EV","Energy","Climate","SaaS"],                thesisScore:82, signals:[{date:"2024-11",type:"Pilot",text:"Pilot with 3 fleet operators in Texas grid"},{date:"2024-10",type:"Hire",text:"Ex-Tesla Energy engineer joined as CTO"}] },
  { id:"c15", name:"Synaptic CRM",       website:"synapticcrm.com",      sector:"Enterprise SaaS",  stage:"Seed",     location:"Denver, CO",          founded:2023, employees:"11-50",  arr:"$0.5M", raised:"$3M",    description:"CRM purpose-built for VC funds with relationship tracking, portfolio monitoring, and LP reporting.",                    tags:["VC Tools","CRM","SaaS","Enterprise"],          thesisScore:90, signals:[{date:"2024-11",type:"Launch",text:"Released LP portal with automated metrics"},{date:"2024-10",type:"Customer",text:"25 VC funds in beta"}] },
  { id:"c16", name:"Arion Protocol",     website:"arion.xyz",            sector:"Web3",             stage:"Pre-Seed", location:"Remote",              founded:2024, employees:"1-10",   arr:"$0",    raised:"$1.2M",  description:"Cross-chain liquidity protocol for institutional DeFi with compliance-first architecture.",                              tags:["Web3","DeFi","Protocol","Institutional"],      thesisScore:38, signals:[{date:"2024-10",type:"Launch",text:"Testnet launch with 500 validators"}] },
  { id:"c17", name:"Lumen Learning",     website:"lumenlearning.ai",     sector:"EdTech",           stage:"Seed",     location:"New York, NY",        founded:2023, employees:"11-50",  arr:"$0.4M", raised:"$3.5M",  description:"Adaptive AI tutor for professional upskilling with personalized learning paths tied to career outcomes.",               tags:["EdTech","AI","Upskilling","B2B2C"],            thesisScore:67, signals:[{date:"2024-10",type:"Partnership",text:"Partnership with 3 Fortune 500 HR teams"},{date:"2024-09",type:"Milestone",text:"10,000 learners onboarded"}] },
  { id:"c18", name:"Callisto Maps",      website:"callistomaps.com",     sector:"GeoSpatial",       stage:"Series A", location:"Seattle, WA",         founded:2021, employees:"51-200", arr:"$4.1M", raised:"$16M",   description:"Real-time geospatial intelligence platform for insurance underwriting and catastrophe risk modeling.",                  tags:["GeoSpatial","Insurance","Climate Risk","B2B"], thesisScore:74, signals:[{date:"2024-11",type:"Customer",text:"Signed 2 top-10 P&C insurers"},{date:"2024-10",type:"Funding",text:"Raised $16M Series A"}] },
  { id:"c19", name:"Opal Commerce",      website:"opalcommerce.com",     sector:"Commerce Tech",    stage:"Seed",     location:"Los Angeles, CA",     founded:2023, employees:"11-50",  arr:"$0.7M", raised:"$4M",    description:"AI-powered merchandising and dynamic pricing engine for mid-market DTC brands.",                                        tags:["Commerce","AI","Pricing","DTC"],               thesisScore:64, signals:[{date:"2024-10",type:"Hire",text:"Ex-Shopify PM joined as CPO"},{date:"2024-09",type:"Customer",text:"12 brands processing $120M GMV"}] },
  { id:"c20", name:"Tether Security",    website:"tethersecurity.ai",    sector:"Cybersecurity",    stage:"Seed",     location:"Austin, TX",          founded:2023, employees:"11-50",  arr:"$1.3M", raised:"$7M",    description:"Identity security platform detecting insider threats and compromised credentials in real-time.",                         tags:["Cybersecurity","Identity","AI","B2B"],         thesisScore:86, signals:[{date:"2024-11",type:"Funding",text:"$7M seed from CRV and Founders Fund"},{date:"2024-10",type:"Launch",text:"SOC2 Type II certified at launch"}] },
];

export const DEFAULT_THESIS = {
  fundName: "Apex Ventures",
  thesis: "We back technical founders building AI-native, B2B software companies that create durable enterprise value through proprietary data or workflow moats. Focus on Seed to Series A, US-based.",
  keywords: ["AI","ML","B2B","enterprise","infrastructure","automation","SaaS","developer tools"],
  sectors: ["AI/ML","Developer Tools","Cybersecurity","Data & Analytics","Fintech"],
  stages: ["Pre-Seed","Seed"],
  minScore: 70,
};

export const SIGNAL_COLORS = {
  Funding: "#4f7cff", Hire: "#b47fff", Launch: "#00d4a0",
  Partnership: "#f5a623", Customer: "#00d4a0", Milestone: "#4f7cff",
  Research: "#7bcfff", Blog: "#8890a8", Pilot: "#f5a623", Contract: "#00d4a0",
};
